// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllChecks(arg1) {
  return window['go']['main']['App']['AllChecks'](arg1);
}

export function BackUpFile(arg1) {
  return window['go']['main']['App']['BackUpFile'](arg1);
}

export function ChangeFileInfo(arg1) {
  return window['go']['main']['App']['ChangeFileInfo'](arg1);
}

export function DelChecks(arg1) {
  return window['go']['main']['App']['DelChecks'](arg1);
}

export function DesktopPath() {
  return window['go']['main']['App']['DesktopPath']();
}

export function DeviceInfo() {
  return window['go']['main']['App']['DeviceInfo']();
}

export function EditHostsFile(arg1) {
  return window['go']['main']['App']['EditHostsFile'](arg1);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenThisFile(arg1) {
  return window['go']['main']['App']['OpenThisFile'](arg1);
}

export function ReadHostsFile() {
  return window['go']['main']['App']['ReadHostsFile']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveTime(arg1, arg2) {
  return window['go']['main']['App']['SaveTime'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
